In [1]:
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import  MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

---

In [6]:
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

lyrics_bbb = ['https://www.lyrics.com/album/630396/Backstreet-Boys-Backstreet%27s-Back',
              'https://www.lyrics.com/album/402023/Millennium',
              'https://www.lyrics.com/album/505594/Black-%26-Blue',
              'https://www.lyrics.com/album/778264/Never-Gone',
              'https://www.lyrics.com/album/1212413/Unbreakable',
              'https://www.lyrics.com/album/1642579/This-Is-Us',
              'https://www.lyrics.com/album/3686233/In-a-World-Like-This',
              'https://www.lyrics.com/album/3762485/DNA']

lyrics_tt = ['https://www.lyrics.com/album/1914738/Take-That-%26-Party-Everything-Changes-Nobody-Else',
             'https://www.lyrics.com/album/939819/Beautiful-World',
             'https://www.lyrics.com/album/1882831/The-Circus',
             'https://www.lyrics.com/album/1706230/The-Greatest-Day----Take-That-Present%3A-The-Circus-Live',
             'https://www.lyrics.com/album/2060663/Progress',
             'https://www.lyrics.com/album/2219105/Progressed',
             'https://www.lyrics.com/album/3103897/III',
             'https://www.lyrics.com/album/3480543/Wonderland',
             'https://www.lyrics.com/album/3732151/Odyssey']

In [7]:
lyrics = lyrics_tt

---

In [130]:
def scraping_albums(lyrics):
    """not today"""

songurls = []
album = []

for i in lyrics:
    r = requests.get(i, headers=headers)
    html = r.text
    print(r)
    mysoup = BeautifulSoup(html, 'html.parser')
    
    for i in mysoup.find_all('table', attrs={'class': 'table tdata'})[0].find_all('a'):
        url = i.get('href')
        if '/lyric/' in url:
            album.append(url)
             
    for i in album:
        songurls.append('https://www.lyrics.com'+i)
        
for i in songurls:
    var = requests.get(i, headers=headers)
    html_lyrics = var.text
    mysoup_lyrics = BeautifulSoup(html_lyrics, 'html.parser')
    k = mysoup_lyrics.find_all('pre')[0].text
    open(f'./data/lyrics.txt', 'a').write(k)
    

---

In [42]:
lyrics_file_bbb = open('./data/lyrics_bbb.txt','r').read()

In [45]:
lyrics_file_bbb = lyrics_file_bbb.splitlines()

In [46]:
clean_lyrics_bbb = []
pattern = r"[^a-z-A-Z0-9]"

for i in lyrics_file_bbb:
    clean = re.sub(pattern, ' ', i.lower())
    clean_lyrics_bbb.append(clean)

In [47]:
bbb = clean_lyrics_bbb

In [48]:
bbb

['everybody grove to the music',
 'everybody jam',
 '',
 'oh  hey',
 '',
 'we ve been waiting so long',
 'just can t hold it back no more',
 'creepin  up and down now',
 'it s time for me to let it go',
 'if you really wanna see',
 'what we can do for you',
 'send the crazy wildin  static',
 'sing it',
 '',
 'jam on  cause backstreet s got it',
 'come on now everybody',
 'we ve got it goin  on for years',
 '',
 'jam on  cause backstreet s got it',
 'come on now everybody',
 'we ve got it goin  on for years',
 '',
 'we ve got it goin  on for years',
 'we ve got it goin  on for years',
 '',
 'well i m creepin  up on your left',
 'straight up funky when i get with you',
 'keep it ruthless when i get wet',
 'keep the party packed in my corner',
 'tough like granite to keep the crowd hype',
 'get up on this just to get right',
 'what you want is what you gonna get',
 'backstreet s got the special effects  uh',
 '',
 'if you really wanna see',
 'what we can do for you  oh',
 'i ll send the c

---

In [18]:
lyrics_file_tt = open('./data/lyrics_tt.txt','r').read()

In [49]:
lyrics_file_tt = lyrics_file_tt.splitlines()

In [50]:
clean_lyrics_tt = []
pattern = r"[^a-z-A-Z0-9]"

for i in lyrics_file_tt:
    clean = re.sub(pattern, ' ', i.lower())
    clean_lyrics_tt.append(clean)

In [51]:
clean_lyrics_tt

['woah  woah  woah  woah  woah  yeah  woah  yeah',
 '',
 'i thought i found love',
 'with somebody else s girl  yeah',
 'ooh',
 '',
 'walkin  round feeling so broken-hearted',
 'lost in a different world',
 'then you came in my life',
 'bought me back to reality someday',
 'now i don t need a fantasy',
 'you re the only one i need',
 '',
 'i found heaven  sweet heaven baby',
 'on the wings of love',
 'i found heaven  sweet heaven baby',
 'on the wings of love',
 'ooh',
 '',
 'i will never  no i ll never',
 'i will never lose my way again',
 'ooh yeah',
 '',
 'i thought you d soon be my girl',
 'but my imagination was running wild',
 'ooh',
 'i wouldn t listen to a single soul',
 'deep in a sense of denial',
 'but then you rescued me baby',
 'opened my eyes and made me see you babe',
 'what real love can be',
 '',
 'you re the angel that i need',
 '',
 'i found heaven  sweet heaven baby',
 'on the wings of love',
 'i found heaven  sweet heaven baby',
 'on the wings of love',
 'ooh',
 ''

In [52]:
tt = clean_lyrics_tt

In [54]:
len(bbb)

31870

In [53]:
len(tt)

36022

In [55]:
bbb_tt = bbb + tt

In [57]:
bbb_tt

['everybody grove to the music',
 'everybody jam',
 '',
 'oh  hey',
 '',
 'we ve been waiting so long',
 'just can t hold it back no more',
 'creepin  up and down now',
 'it s time for me to let it go',
 'if you really wanna see',
 'what we can do for you',
 'send the crazy wildin  static',
 'sing it',
 '',
 'jam on  cause backstreet s got it',
 'come on now everybody',
 'we ve got it goin  on for years',
 '',
 'jam on  cause backstreet s got it',
 'come on now everybody',
 'we ve got it goin  on for years',
 '',
 'we ve got it goin  on for years',
 'we ve got it goin  on for years',
 '',
 'well i m creepin  up on your left',
 'straight up funky when i get with you',
 'keep it ruthless when i get wet',
 'keep the party packed in my corner',
 'tough like granite to keep the crowd hype',
 'get up on this just to get right',
 'what you want is what you gonna get',
 'backstreet s got the special effects  uh',
 '',
 'if you really wanna see',
 'what we can do for you  oh',
 'i ll send the c

---

In [58]:
cv = CountVectorizer(stop_words='english')

In [59]:
cv.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides'

In [60]:
vectorized_corpus = cv.fit_transform(bbb_tt)

In [61]:
cv.vocabulary_

{'everybody': 713,
 'grove': 975,
 'music': 1502,
 'jam': 1183,
 'oh': 1563,
 'hey': 1062,
 've': 2463,
 'waiting': 2485,
 'long': 1333,
 'just': 1202,
 'hold': 1081,
 'creepin': 477,
 'time': 2350,
 'let': 1279,
 'really': 1794,
 'wanna': 2495,
 'send': 1961,
 'crazy': 473,
 'wildin': 2552,
 'static': 2175,
 'sing': 2045,
 'cause': 318,
 'backstreet': 118,
 'got': 950,
 'come': 410,
 'goin': 935,
 'years': 2623,
 'left': 1276,
 'straight': 2206,
 'funky': 890,
 'ruthless': 1894,
 'wet': 2539,
 'party': 1617,
 'packed': 1600,
 'corner': 449,
 'tough': 2375,
 'like': 1303,
 'granite': 958,
 'crowd': 486,
 'hype': 1122,
 'right': 1854,
 'want': 2496,
 'gonna': 943,
 'special': 2133,
 'effects': 671,
 'uh': 2423,
 'll': 1322,
 'groove': 972,
 'oni': 1577,
 'asked': 99,
 'walk': 2488,
 'halfway': 997,
 'world': 2596,
 'kiss': 1224,
 'far': 760,
 'love': 1353,
 'sun': 2233,
 'stars': 2167,
 'moon': 1482,
 'lead': 1261,
 'won': 2583,
 'lose': 1343,
 'way': 2522,
 'believe': 155,
 'darkest': 

In [62]:
vectorized_corpus.shape

(67892, 2650)

In [63]:
vectorized_corpus

<67892x2650 sparse matrix of type '<class 'numpy.int64'>'
	with 141907 stored elements in Compressed Sparse Row format>

In [64]:
print(vectorized_corpus)

  (0, 713)	1
  (0, 975)	1
  (0, 1502)	1
  (1, 713)	1
  (1, 1183)	1
  (3, 1563)	1
  (3, 1062)	1
  (5, 2463)	1
  (5, 2485)	1
  (5, 1333)	1
  (6, 1202)	1
  (6, 1081)	1
  (7, 477)	1
  (8, 2350)	1
  (8, 1279)	1
  (9, 1794)	1
  (9, 2495)	1
  (11, 1961)	1
  (11, 473)	1
  (11, 2552)	1
  (11, 2175)	1
  (12, 2045)	1
  (14, 1183)	1
  (14, 318)	1
  (14, 118)	1
  :	:
  (67880, 1279)	1
  (67880, 1353)	1
  (67880, 2617)	1
  (67881, 2006)	1
  (67882, 1279)	1
  (67882, 1353)	1
  (67882, 2617)	1
  (67883, 1404)	1
  (67884, 2006)	1
  (67885, 1563)	1
  (67885, 1062)	1
  (67885, 410)	1
  (67886, 733)	1
  (67886, 1300)	1
  (67887, 1563)	1
  (67887, 410)	1
  (67887, 2619)	1
  (67888, 1279)	1
  (67888, 2006)	1
  (67889, 1202)	1
  (67889, 1279)	1
  (67889, 2006)	1
  (67890, 1300)	1
  (67890, 2006)	1
  (67891, 2006)	1


In [65]:
vectorized_corpus.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [66]:
df = pd.DataFrame(vectorized_corpus.todense(),columns=cv.get_feature_names())

In [67]:
tfidf = TfidfTransformer()

In [68]:
tfidf_matr = tfidf.fit_transform(vectorized_corpus)

In [69]:
idf_df = pd.DataFrame(tfidf.idf_, index=cv.get_feature_names(),columns=["idf_weights"])
idf_df.sort_values(by=['idf_weights'])

idf_weights
love          3.809143
don           4.208516
know          4.246397
want          4.276364
just          4.359695
...                ...
obsessive    11.432541
details      11.432541
deepest      11.432541
chest        11.432541
stolen       11.432541

[2650 rows x 1 columns]

In [70]:
tfidf_df = pd.DataFrame(tfidf_matr.todense(),columns=cv.get_feature_names())

In [71]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [72]:
tfidf_df.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [73]:
X = tfidf_df.values
y = ["Backstreet Boys"] * len(bbb) + ['Take That'] * len(tt)

---

In [75]:
m = LogisticRegression(max_iter = 1000)
m.fit(X, y)
m.score(X, y)

0.7569816767807694

---

In [141]:
new_docs = open('./data/test.txt','r').read()

In [142]:
new_docs = new_docs.splitlines()

In [143]:
new_doc_vect = cv.transform(new_docs).todense()
new_doc_tfidf = tfidf.transform(new_doc_vect).todense()

In [144]:
m.predict(new_doc_tfidf)[0]

'Backstreet Boys'

In [145]:
m.predict_proba(new_doc_tfidf)

array([[0.50043062, 0.49956938]])

---